import React, { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, CircleDollarSign, Download, FileText, Plus, Search, Wallet } from 'lucide-react';
import { money, shortDate, STATUS, today } from './model.js';
import { financialCsv, financialSummary, shiftMonth } from './finance.js';
import { download } from './exports.js';
import './finance.css';

export default function Finance({ state, onEdit, onBooking }) {
  const [period, setPeriod] = useState(() => today().slice(0, 7));
  const [filter, setFilter] = useState('all');
  const [query, setQuery] = useState('');
  const report = useMemo(() => financialSummary(state, period), [state, period]);
  const currency = state.property.currency;
  const monthLabel = value => new Intl.DateTimeFormat('hu-HU', { year: 'numeric', month: 'long' }).format(new Date(`${value}-01T12:00:00Z`));
  const months = [...new Set([...Array.from({ length: 25 }, (_, i) => shiftMonth(today().slice(0, 7), i - 12)), ...state.bookings.map(booking => booking.from.slice(0, 7)), period])].sort();
  const visible = report.rows.filter(row => (filter === 'all' || (filter === 'unpaid' ? row.remaining > 0 : row.remaining === 0)) && `${row.booking.name} ${row.room?.name || ''}`.toLocaleLowerCase('hu').includes(query.trim().toLocaleLowerCase('hu')));
  const stats = [[FileText, 'Rögzített szállásdíj', report.total, `${report.rows.length} foglalás teljes díja`, 'green'], [Wallet, 'Eddig befizetve', report.paid, 'A foglalásokhoz rögzített befizetések', 'sage'], [CircleDollarSign, 'Még befizetendő', report.remaining, `${report.unpaidCount} foglalásnál maradt összeg`, 'sand']];
  return <>
    <div className="page-heading"><div><div className="eyebrow">ÁTLÁTHATÓ DÍJAK, KEVESEBB FEJBEN SZÁMOLÁS</div><h1>Díjak és befizetések</h1><p>A kiválasztott hónapban érkező foglalásaid teljes szállásdíja és rögzített befizetései.</p></div><button className="btn secondary" disabled={!visible.length} onClick={() => download(`pensiunekit-dijak-${period}.csv`, financialCsv(visible, currency), 'text/csv;charset=utf-8')}><Download size={16}/>Lista letöltése</button></div>
    <div className="finance-period"><div><button className="icon-btn" aria-label="Előző érkezési hónap" onClick={() => setPeriod(shiftMonth(period, -1))}><ChevronLeft size={19}/></button><label><CalendarDays size={17}/><select aria-label="Érkezési hónap" value={period} onChange={e => setPeriod(e.target.value)}>{months.map(month => <option key={month} value={month}>{monthLabel(month)}</option>)}</select></label><button className="icon-btn" aria-label="Következő érkezési hónap" onClick={() => setPeriod(shiftMonth(period, 1))}><ChevronRight size={19}/></button></div><button className="mini-btn" onClick={() => setPeriod(today().slice(0, 7))}>Ez a hónap</button></div>
    <div className="stats-grid finance-stats">{stats.map(([Icon, title, value, detail, color]) => <div className="stat-card" key={title}><div className="stat-top"><span>{title}</span><span className={`stat-icon ${color}`}><Icon size={18}/></span></div><strong>{money(value, currency)}</strong><small>{detail}</small></div>)}</div>
    <div className="finance-scope"><FileText size={17}/><p>Az összegek a kiválasztott hónapban <strong>érkező foglalások teljes tartózkodására</strong> vonatkoznak. A befizetés a foglalásban megadott összeg; a rendszer nem ellenőrzi a banki jóváírást. A lemondott foglalások kimaradnak{report.cancelledCount > 0 ? ` (${report.cancelledCount} lemondás ebben a hónapban)` : ''}.</p></div>
    <section className="panel finance-list"><div className="panel-title"><h2>Foglalások pénzügyi állapota</h2><span>{visible.length} / {report.rows.length} foglalás</span></div><div className="finance-tools"><div className="finance-filters" role="group" aria-label="Befizetés szerinti szűrés">{[['all', 'Összes'], ['unpaid', 'Még befizetendő'], ['paid', 'Rendezett']].map(([value, title]) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{title}{value === 'unpaid' && <span>{report.unpaidCount}</span>}</button>)}</div><label className="search-box"><Search size={16}/><input aria-label="Keresés a díjak között" placeholder="Vendég vagy szállásegység…" value={query} onChange={e => setQuery(e.target.value)}/></label></div>
      {visible.length ? <div className="finance-table"><div className="finance-table-head"><span>Vendég / tartózkodás</span><span>Teljes díj</span><span>Befizetve</span><span>Még befizetendő</span><span/></div>{visible.map(row => <div className="finance-row" key={row.booking.id}><div className="finance-guest"><strong>{row.booking.name}</strong><span>{row.room?.name} · {shortDate(row.booking.from)} – {shortDate(row.booking.to)}</span><small>{STATUS[row.booking.status]}</small></div><div className="finance-amount"><span>Teljes díj</span><strong>{money(row.total, currency)}</strong></div><div className="finance-amount"><span>Befizetve</span><strong>{money(row.paid, currency)}</strong></div><div className={`finance-amount ${row.remaining > 0 ? 'remaining' : 'settled'}`}><span>Még befizetendő</span><strong>{row.remaining > 0 ? money(row.remaining, currency) : <><Check size={13}/>Rendezett</>}</strong></div><button className="icon-btn" aria-label={`${row.booking.name} díjainak és befizetésének szerkesztése`} onClick={() => onEdit(row.booking)}><ArrowRight size={17}/></button></div>)}</div> : <div className="empty"><Wallet size={30}/><h3>{report.rows.length ? 'Ehhez a szűréshez nincs találat' : 'Ebben a hónapban még nincs érkező foglalás'}</h3><p>{report.rows.length ? 'Válassz másik szűrőt, vagy módosítsd a keresést.' : 'Válassz másik érkezési hónapot, vagy rögzíts egy új foglalást.'}</p>{report.rows.length ? <button className="btn secondary" onClick={() => { setFilter('all'); setQuery(''); }}>Összes foglalás mutatása</button> : <button className="btn" onClick={onBooking}><Plus size={16}/>Új foglalás</button>}</div>}
    </section>
    {report.sources.length > 0 && <section className="panel finance-sources"><div className="panel-title"><h2>Honnan érkeztek ezek a foglalások?</h2></div><p className="quiet">A foglalásnál kézzel megadott források, a teljes szállásdíj alapján.</p><div>{report.sources.map(source => <div key={source.source}><div><strong>{source.source}</strong><span>{source.count} foglalás · {money(source.total, currency)}</span></div><div className="finance-source-bar"><span style={{ width: `${report.total ? source.total / report.total * 100 : 0}%` }}/></div></div>)}</div></section>}
    <p className="finance-note">Ez az áttekintés a saját nyilvántartásodat segíti. A szállásdíjakat és a befizetéseket a foglalás megnyitásával módosíthatod. A letöltött lista az aktuális szűrés eredményét tartalmazza.</p>
  </>;
}
