const escape = value => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x]));
export const GUIDE_FIELDS = { tagline: 'Rövid köszöntő', breakfast: 'Reggeli', parking: 'Parkolás', rules: 'Házirend' };
const DICT = {
  hu: { title: 'Vendégútmutató', welcome: 'Szeretettel köszöntjük!', intro: 'Minden fontos tudnivaló a kényelmes pihenéshez.', checkin: 'Érkezés ettől', checkout: 'Távozás eddig', network: 'Hálózat', password: 'Jelszó', breakfast: 'Reggeli', parking: 'Parkolás', rules: 'Házirend', contact: 'Elérhetőség', fallback: 'A házigazda ezt az információt magyarul adta meg.' },
  ro: { title: 'Ghidul oaspetelui', welcome: 'Bine ați venit!', intro: 'Informațiile importante pentru o ședere plăcută.', checkin: 'Check-in de la', checkout: 'Check-out până la', network: 'Rețea', password: 'Parolă', breakfast: 'Mic dejun', parking: 'Parcare', rules: 'Regulamentul casei', contact: 'Contact', fallback: 'Gazda a oferit această informație în limba maghiară.' },
  en: { title: 'Guest guide', welcome: 'Welcome to our guesthouse!', intro: 'Everything you need for a comfortable stay.', checkin: 'Check-in from', checkout: 'Check-out until', network: 'Network', password: 'Password', breakfast: 'Breakfast', parking: 'Parking', rules: 'House rules', contact: 'Contact', fallback: 'The host provided this information in Hungarian.' },
  de: { title: 'Gäste-Guide', welcome: 'Herzlich willkommen!', intro: 'Alle wichtigen Informationen für einen angenehmen Aufenthalt.', checkin: 'Anreise ab', checkout: 'Abreise bis', network: 'Netzwerk', password: 'Passwort', breakfast: 'Frühstück', parking: 'Parken', rules: 'Hausordnung', contact: 'Kontakt', fallback: 'Der Gastgeber hat diese Information auf Ungarisch angegeben.' },
};
export function validGuideTranslations(value) {
  if (value === undefined) return true;
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  return Object.entries(value).every(([language, fields]) => ['ro','en','de'].includes(language) && fields && typeof fields === 'object' && !Array.isArray(fields) && Object.entries(fields).every(([key, text]) => Object.hasOwn(GUIDE_FIELDS, key) && typeof text === 'string' && text.length <= 4000));
}
export function multilingualGuideHtml(p, selected = 'hu') {
  const languages = Object.keys(DICT); const initial = languages.includes(selected) ? selected : 'hu';
  const translations = validGuideTranslations(p.guideTranslations) ? p.guideTranslations || {} : {};
  const translated = (lang, key) => translations[lang]?.[key]?.trim() || p[key] || '';
  const radios = languages.map(lang => `<input class="language-radio" type="radio" name="language" id="language-${lang}" aria-label="${{hu:'Magyar',ro:'Română',en:'English',de:'Deutsch'}[lang]}"${lang === initial ? ' checked' : ''}>`).join('');
  const contents = languages.map(lang => {
    const d = DICT[lang];
    const custom = key => {
      const text = translated(lang, key); if (!text) return '';
      const fallback = lang !== 'hu' && !translations[lang]?.[key]?.trim();
      return `<section><h2>${d[key]}</h2>${fallback ? `<small class="fallback">${d.fallback}</small>` : ''}<p${fallback ? ' lang="hu"' : ''}>${escape(text)}</p></section>`;
    };
    const tagline = translated(lang, 'tagline');
    return `<article class="guide-language guide-${lang}" lang="${lang}"><header><small>${d.title}</small><h1>${escape(p.name || 'Vendégházunk')}</h1>${tagline ? `<p>${escape(tagline)}</p>` : ''}</header><main><section><h2>${d.welcome}</h2><p>${d.intro}</p><div class="guide-times"><div><small>${d.checkin}</small><strong>${escape(p.checkin)}</strong></div><div><small>${d.checkout}</small><strong>${escape(p.checkout)}</strong></div></div></section>${p.wifiName ? `<section><h2>WiFi</h2><dl><dt>${d.network}</dt><dd>${escape(p.wifiName)}</dd><dt>${d.password}</dt><dd>${escape(p.wifiPass)}</dd></dl></section>` : ''}${custom('breakfast')}${custom('parking')}${custom('rules')}<section><h2>${d.contact}</h2><p>${escape([p.address,p.phone,p.email].filter(Boolean).join('\n'))}</p></section></main><footer>${escape(p.name)} · PensiuneKit</footer></article>`;
  }).join('');
  const selectors = languages.map(lang => `#language-${lang}:checked~.guide-content .guide-${lang}{display:block}#language-${lang}:checked~nav label[for="language-${lang}"]{background:#244836;color:white}#language-${lang}:focus-visible~nav label[for="language-${lang}"]{outline:3px solid #a6ba61;outline-offset:3px}`).join('');
  return `<!doctype html><html lang="${initial}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(p.name)} · ${DICT[initial].title}</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f5ef;color:#24382c;font:16px/1.65 system-ui,sans-serif}.language-radio{position:absolute;width:1px;height:1px;clip-path:inset(50%)}nav{display:flex;justify-content:center;gap:8px;padding:16px;background:#fff;position:sticky;top:0;border-bottom:1px solid #dfe4da}nav label{padding:8px 15px;cursor:pointer;border-radius:8px;font-weight:600}.guide-language{display:none}header{background:#244836;color:white;text-align:center;padding:40px 20px}header small{text-transform:uppercase;letter-spacing:2px}h1{font:normal 36px/1.2 Georgia,serif;margin:16px 0}h2{font:normal 24px/1.3 Georgia,serif;margin:0 0 12px}p{white-space:pre-line;overflow-wrap:anywhere;margin:8px 0}main{max-width:680px;margin:auto;padding:14px 16px}section{background:white;border:1px solid #e0e5db;border-radius:14px;padding:22px;margin:12px 0}.guide-times{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.guide-times div{padding:15px;background:#f1f4eb;border-radius:10px}.guide-times small,.guide-times strong{display:block}.guide-times strong{font-size:23px}dl{display:grid;grid-template-columns:auto 1fr;gap:12px}dd{margin:0;overflow-wrap:anywhere;font-weight:600}.fallback{display:block;color:#68735d;font-size:12px}footer{text-align:center;padding:24px;color:#657368;font-size:12px}${selectors}@media(max-width:360px){nav{gap:4px}nav label{padding:8px 12px}section{padding:18px}h1{font-size:30px}}</style></head><body>${radios}<nav aria-label="Language / Nyelv">${languages.map(lang => `<label for="language-${lang}">${lang.toUpperCase()}</label>`).join('')}</nav><div class="guide-content">${contents}</div></body></html>`;
}
export function qrCardHtml(p, image) {
  if (!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(image)) throw new Error('Először készíts QR-kódot.');
  return `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Szobai QR-kártya · ${escape(p.name)}</title><style>*{box-sizing:border-box}body{margin:0;padding:30px;background:#f6f5ef;color:#244836;font:16px/1.6 system-ui,sans-serif}.card{max-width:460px;margin:auto;padding:36px;background:white;border:2px solid #244836;border-radius:16px;text-align:center}h1{font:normal 34px Georgia,serif}img{display:block;width:220px;max-width:100%;margin:20px auto}small{display:block;overflow-wrap:anywhere}dl{text-align:left;display:grid;grid-template-columns:auto 1fr;gap:10px;border-top:1px solid #dce3d4;padding-top:20px}dd{margin:0;overflow-wrap:anywhere}button{display:block;margin:0 auto 20px;padding:12px 20px;background:#244836;color:white;border:0;border-radius:8px;font:inherit;cursor:pointer}@page{size:A5 portrait;margin:12mm}@media print{body{background:white;padding:0}button{display:none}.card{max-width:none;border-radius:0;break-inside:avoid}}</style></head><body><button onclick="window.print()">Kártya nyomtatása / Mentés PDF-ként</button><main class="card"><small>WELCOME · BINE AȚI VENIT · WILLKOMMEN</small><h1>${escape(p.name)}</h1><p>A vendégútmutatód egy beolvasásra.<br>Scan for your guest guide.</p><img src="${image}" alt="Vendégútmutató QR-kód"><small>HU · RO · EN · DE</small><small>${escape(p.guideUrl)}</small>${p.wifiName ? `<dl><dt>WiFi</dt><dd>${escape(p.wifiName)}</dd><dt>Jelszó / Password</dt><dd>${escape(p.wifiPass)}</dd></dl>` : ''}<p>Kellemes pihenést! · Enjoy your stay!</p></main></body></html>`;
}
