import React, { useState } from 'react';
import { ArrowRight, BedDouble, BookOpen, CalendarDays, Check, ChevronDown, CircleCheck, Coffee, Globe, House, Menu, MessageSquare, Mountain, ShieldCheck, X } from 'lucide-react';
import './landing.css';
const FEATURES = [
  [CalendarDays, 'Foglalások, egy helyen.', 'Rögzítsd a telefonon, e-mailben vagy más csatornán érkező foglalásokat. Lásd a szabad időpontokat, és vedd észre az ütközést még időben.'],
  [BedDouble, 'Minden szoba készen áll.', 'Érkezők, távozók, takarítás. Egy gyors pillantás, és tudod, mi a következő teendőd.'],
  [BookOpen, 'Válaszok a vendég zsebében.', 'WiFi, reggeli, parkolás, házirend. Saját vendégútmutató, letölthető oldallal és a webcímedhez készített QR-kóddal.'],
  [MessageSquare, 'Kedves üzenetek, négy nyelven.', 'Visszaigazolás, érkezési tudnivalók, elköszönés. Szerkeszthető magyar, román, angol és német sablonok, a szállásod adataival.'],
  [Globe, 'A szállásod saját weboldala.', 'Mutasd meg a szobáidat, az áraikat és a hely történetét egy letölthető, mobilbarát bemutatkozó oldalon.'],
  [ShieldCheck, 'Mentés, ami kéznél van.', 'Helyi munkaterület, letölthető biztonsági másolat és foglalásexport. A szállásod adatait bármikor magaddal viheted.'],
];
const PLANS = [
  { name: 'Ingyenes', monthly: 0, annual: 0, description: 'Indulj el a saját szállásoddal.', features: ['1 szálláshely munkaterülete', 'Foglalási naptár és szobák', 'Takarítás és napi teendők', 'Vendégútmutató és QR-kód', 'Négynyelvű üzenetsablonok', 'Weboldal- és adatletöltés'] },
  { name: 'Starter', monthly: 12, annual: 9, description: 'A mindennapokhoz, több kényelemmel.', planned: true, features: ['Az Ingyenes csomag funkciói', 'Fiók és több eszközös elérés', 'Automatikus felhőmentés', 'Közzétett vendégútmutató', 'Online szállásbemutatkozó oldal'] },
  { name: 'Pro', monthly: 29, annual: 24, description: 'Ha több vendégházat viszel.', planned: true, featured: true, features: ['A Starter csomag funkciói', 'Legfeljebb 3 szálláshely', 'Szállások közötti gyors váltás', 'Részletes bevételi kimutatások', 'Közös áttekintés a szállásaidról'] },
];
const FAQ = [
  ['Egyetlen kiadó házzal is használhatom?', 'Igen. A kiadó házat egy szállásegységként veheted fel. A naptár, az üzenetsablonok és a vendégútmutató ugyanúgy működik, mint több szoba esetén.'],
  ['Mennyibe kerül, és hol találom az árakat?', 'Az Árak menüpont a csomagokhoz visz. A jelenlegi helyi munkaterület ingyen használható. A Starter és Pro tervezett csomagok; fizetős előfizetés és online fizetés még nem indult el.'],
  ['Összekapcsolódik a Booking.commal vagy az Airbnb-vel?', 'Jelenleg a foglalásokat kézzel rögzíted, és megjelölheted a forrásukat. Automatikus csatornaszinkron nincs bekötve. A naptár a rögzített foglalások közötti ütközést ellenőrzi.'],
  ['A telefonomon is működik?', 'Igen, a munkaterület mobilon is használható. A helyi adatok azon az eszközön és abban a böngészőben maradnak, ahol létrehoztad őket. Másik eszközre a Beállításokban letöltött biztonsági másolatot tudod átvinni.'],
  ['A vendégeknek le kell tölteniük egy alkalmazást?', 'Nem. A vendégútmutató mobilon is megnyitható weboldal. A letöltött útmutatót a saját tárhelyeden teheted közzé, majd a webcíméhez beolvasható QR-kódot készíthetsz.'],
  ['Az üzenetek automatikusan mennek ki?', 'A sablonokat átnézheted, szerkesztheted és másolhatod. Az e-mail gomb a saját leveleződet nyitja meg. Automatikus levélküldés és élő AI-generálás jelenleg nincs beállítva.'],
];
function ProductPreview() {
  const [view, setView] = useState('today');
  return <div className="lp-preview-wrap"><div className="lp-preview">
    <div className="lp-preview-bar"><span className="lp-mini-brand"><Mountain size={17}/> PensiuneKit</span><span className="lp-sample">BEMUTATÓ ADATOK</span></div>
    <div className="lp-preview-body"><div className="lp-preview-heading"><div><span>BORÓKA VENDÉGHÁZ</span><h2>Minden a helyén.</h2></div><span className="lp-preview-avatar">B</span></div>
      <div className="lp-preview-tabs" aria-label="Munkaterület előnézet"><button aria-pressed={view === 'today'} onClick={() => setView('today')}><House size={14}/> Mai áttekintés</button><button aria-pressed={view === 'calendar'} onClick={() => setView('calendar')}><CalendarDays size={14}/> Naptár</button></div>
      <div className="lp-preview-stats">{[['2', 'Érkező vendég'], ['1', 'Távozó vendég'], ['5 / 6', 'Foglalt szoba']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
      {view === 'today' ? <div className="lp-preview-arrivals"><h3>Ma őket várjuk <span>2 foglalás</span></h3>{[['NE', 'Nagy Eszter', 'Fenyő szoba · 2 vendég', '14:00'], ['HM', 'Hannah Müller', 'Családi szoba · 4 vendég', '16:30']].map(([initials, name, room, time]) => <div key={name}><span className="lp-guest-avatar">{initials}</span><span><strong>{name}</strong><small>{room}</small></span><span className="lp-time">{time}</span></div>)}</div> : <div className="lp-preview-calendar"><div className="lp-calendar-head"><span>Szoba</span>{['H', 'K', 'Sze', 'Cs', 'P'].map(day => <span key={day}>{day}</span>)}</div>{[['Fenyő', [0, 1, 1, 1, 0]], ['Családi', [1, 1, 0, 1, 1]], ['Boróka', [0, 0, 1, 1, 1]]].map(([room, days]) => <div key={room}><strong>{room}</strong>{days.map((booked, i) => <span key={i} className={booked ? 'occupied' : ''}>{booked ? 'Foglalt' : 'Szabad'}</span>)}</div>)}<small>A mintanaptárban a foglalások kézzel rögzítettek.</small></div>}
      <div className="lp-preview-task"><CircleCheck size={17}/><span>Fenyő szoba előkészítve</span><span>Kész</span></div>
    </div><a href="#demo" className="lp-preview-link">Nyisd meg a működő demót <ArrowRight size={15}/></a>
  </div><div className="lp-guide-note"><span><BookOpen size={20}/></span><div><strong>A vendégeid is képben lesznek.</strong><small>WiFi, reggeli, házirend — egy útmutatóban.</small></div></div></div>;
}
export default function Landing({ configured }) {
  const [menu, setMenu] = useState(false);
  const [annual, setAnnual] = useState(false);
  return <div className="lp"><a className="skip-link" href="#landing-main">Ugrás a tartalomra</a>
    <header className="lp-header"><div className="lp-header-inner"><a className="lp-brand" href="#"><span><Mountain size={24}/></span>Pensiune<span>Kit</span></a><button className="lp-menu" aria-label={menu ? 'Menü bezárása' : 'Menü megnyitása'} aria-expanded={menu} aria-controls="lp-nav" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><nav id="lp-nav" className={menu ? 'open' : ''} aria-label="Weboldal navigáció"><a href="#features" onClick={() => setMenu(false)}>Funkciók</a><a href="#how" onClick={() => setMenu(false)}>Így működik</a><a href="#pricing" onClick={() => setMenu(false)}>Árak</a><a href="#questions" onClick={() => setMenu(false)}>Kérdések</a><a className="lp-login" href="#app">{configured ? 'Belépés' : 'Saját munkaterület'}</a><a className="lp-button small" href="#demo">Demó kipróbálása <ArrowRight size={15}/></a></nav></div></header>
    <main id="landing-main"><section className="lp-hero lp-container"><div className="lp-hero-copy"><div className="lp-label"><span/> KIS SZÁLLÁSHELYEK. KÖNNYEBB MINDENNAPOK.</div><h1>Vendégházad<br/>rendben.<br/><span>Vendégeid otthon.</span></h1><p>Foglalások, szobák és vendégkommunikáció egy helyen. Hogy több időd maradjon arra, amit a vendégeid igazán szeretnek: a figyelmedre.</p><div className="lp-hero-actions"><a className="lp-button" href="#demo">Kipróbálom a demót <ArrowRight size={17}/></a><a className="lp-button outline" href="#pricing">Megnézem az árakat</a></div><div className="lp-hero-checks"><span><Check size={15}/> Fiók nélkül kipróbálható</span><span><Check size={15}/> Ingyenes indulás</span></div></div><ProductPreview/></section>
      <div className="lp-audience"><div className="lp-container"><span>A TE MÉRETEDRE TERVEZVE</span><div>{[[House, 'Családi panziók'], [Mountain, 'Vendégházak'], [Coffee, 'Falusi szállások'], [BedDouble, 'Kiadó házak']].map(([Icon, title]) => <span key={title}><Icon size={18}/>{title}</span>)}</div></div></div>
      <section className="lp-section lp-container" id="features"><div className="lp-section-heading"><div><div className="lp-label">KEVESEBB FEJBEN TARTOTT RÉSZLET</div><h2>A napi teendőid.<br/><span>Egy átlátható munkaterületen.</span></h2></div><p>Amikor te vagy a házigazda, a recepciós és a szervező is, jól jön egy hely, ahol minden összeér.</p></div><div className="lp-features">{FEATURES.map(([Icon, title, text], i) => <article key={title}><div><span className="lp-feature-icon"><Icon size={23}/></span><small>0{i + 1}</small></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="lp-focus lp-container"><div><div className="lp-label">KIS SZÁLLÁS. NAGY ODAFIGYELÉS.</div><h2>A személyes vendéglátáshoz<br/>rendezett háttér kell.</h2><p>Az érkezés előtti kedves üzenet. A tiszta szoba. A jó túratipp. A PensiuneKit segít kézben tartani a részleteket.</p><a href="#demo" className="lp-button lime">Megnézem a munkaterületet <ArrowRight size={17}/></a></div><div className="lp-focus-list">{[['01', 'Tudd, ki érkezik.', 'Napi áttekintés és foglalási naptár.'], ['02', 'Készülj fel nyugodtan.', 'Szobaállapot és takarítási teendők.'], ['03', 'Fogadd őket figyelemmel.', 'Személyre szabható üzenetek és útmutató.']].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><Check size={18}/></div>)}</div></section>
      <section className="lp-section lp-container" id="how"><div className="lp-center-heading"><div className="lp-label">EGYSZERŰ INDULÁS</div><h2>A saját szállásod.<br/>Néhány lépésre.</h2><p>Kezdj mintafoglalásokkal, vagy rögtön a saját adataiddal.</p></div><div className="lp-steps">{[['01', 'Add meg a szállásodat.', 'Név, szobák, árak, érkezési tudnivalók. Amit a házadról már úgyis tudsz.'], ['02', 'Rögzítsd a foglalásokat.', 'Vendégek, időpontok, előlegek. A naptár és az áttekintés ezekből áll össze.'], ['03', 'Legyen kéznél minden.', 'Teendők, üzenetek, vendégútmutató. A következő érkezés előtt már könnyebb dolgod lesz.']].map(([n, title, text]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="lp-pricing" id="pricing"><div className="lp-container"><div className="lp-center-heading"><div className="lp-label">ÁTLÁTHATÓ CSOMAGOK</div><h2>Kicsiben kezdesz.<br/><span>Veled együtt fejlődünk.</span></h2><p>A jelenlegi munkaterület ingyenes. Ezekkel a csomagokkal készülünk a következő lépésre.</p></div><div className="lp-billing" role="group" aria-label="Csomagárak időszaka"><button aria-pressed={!annual} onClick={() => setAnnual(false)}>Havi fizetés</button><button aria-pressed={annual} onClick={() => setAnnual(true)}>Éves fizetés <span>Akár −25%</span></button></div><div className="lp-plans">{PLANS.map(plan => <article key={plan.name} className={plan.featured ? 'lp-plan featured' : 'lp-plan'}><div className="lp-plan-top"><h3>{plan.name}</h3><span className={plan.planned ? 'lp-plan-status planned' : 'lp-plan-status'}>{plan.planned ? 'Tervezett csomag' : 'Most elérhető'}</span></div><p className="lp-plan-description">{plan.description}</p><div className="lp-price"><strong>{annual ? plan.annual : plan.monthly}<span> €</span></strong><span>/ hó</span></div><p className="lp-price-period">{plan.monthly === 0 ? 'Díjmentes helyi munkaterület' : annual ? `${plan.annual * 12} € / év · éves fizetéssel` : 'Havi fizetéssel'}</p><a className={`lp-button ${plan.featured ? 'lime' : plan.planned ? 'outline' : ''}`} href={plan.planned ? '#demo' : '#app'}>{plan.planned ? 'Megnézem a demót' : 'Elkezdem ingyen'}<ArrowRight size={16}/></a><div className="lp-plan-features-label">{plan.planned ? 'AMIT A CSOMAGBA TERVEZÜNK' : 'AMIT MOST HASZNÁLHATSZ'}</div><ul>{plan.features.map(feature => <li key={feature}><Check size={16}/>{feature}</li>)}</ul></article>)}</div><div className="lp-pricing-note"><ShieldCheck size={19}/><p><strong>Most díjmentesen kipróbálhatod.</strong> A fizetős csomagok még nem vásárolhatók meg. Nincs bankkártyaadat-kérés vagy automatikus terhelés; a csomagok ára és tartalma az indulásig változhat.</p></div></div></section>
      <section className="lp-section lp-container lp-faq" id="questions"><div><div className="lp-label">JÓ, HA ELŐRE TUDOD</div><h2>Kérdések?<br/><span>Itt a válasz.</span></h2><p>Ismerd meg a működést, mielőtt elkezded.</p><a href="#pricing" className="lp-text-link">Vissza az árakhoz <ArrowRight size={16}/></a></div><div>{FAQ.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18}/></summary><p>{answer}</p></details>)}</div></section>
      <section className="lp-final"><div className="lp-container"><span className="lp-label">A KÖVETKEZŐ VENDÉGED MÁR ÉRKEZHET NYUGODTABBAN.</span><h2>Legyen rendben a háttér.<br/>A vendéglátás maradjon személyes.</h2><div><a href="#demo" className="lp-button">Kipróbálom a PensiuneKitet <ArrowRight size={17}/></a><a href="#pricing" className="lp-text-link">Csomagok és árak <ArrowRight size={16}/></a></div><p>Ingyenes bemutató · Fiók nélkül · Saját tempódban</p></div></section>
    </main><footer className="lp-footer lp-container"><a className="lp-brand" href="#"><span><Mountain size={22}/></span>Pensiune<span>Kit</span></a><span>Kis szállás. Nagy odafigyelés.</span><nav aria-label="Lábléc navigáció"><a href="#pricing">Árak</a><a href="#questions">Kérdések</a><span>© {new Date().getFullYear()} PensiuneKit</span></nav></footer>
  </div>;
}
