import React from 'react';
import { ArrowRight, BedDouble, CalendarDays, Check, Coffee, MapPin, Wifi } from 'lucide-react';
import './landing-examples.css';

export default function LandingExamples() {
  return <section className="lp-section lp-container lp-examples" id="examples"><div className="lp-section-heading"><div><div className="lp-label">LÁSD, MIRE JÓ A GYAKORLATBAN</div><h2>Három hétköznapi helyzet.<br/><span>Egy egyszerű segítség.</span></h2></div><p>Telefonon foglaltak? Érkezik a következő család? WiFi-jelszót kérnek? Legyen kéznél a válasz.</p></div><div className="lp-example-grid">
    <article><div className="lp-example-visual"><div className="lp-example-title"><CalendarDays size={17}/>Új foglalás<span>Minta</span></div><div className="lp-mini-field"><small>Vendég neve</small><strong>Kiss Anna</strong></div><div className="lp-mini-dates"><div className="lp-mini-field"><small>Érkezés</small><strong>Október 16.</strong></div><div className="lp-mini-field"><small>Távozás</small><strong>Október 18.</strong></div></div><div className="lp-mini-field"><small>Szoba vagy kiadó ház</small><strong>Fenyő szoba <BedDouble size={14}/></strong></div><div className="lp-mini-saved"><Check size={15}/>Foglalás a helyén.</div></div><div className="lp-example-copy"><span>01 · TELEFONON FOGLALTAK</span><h3>Írd be, és már látod is.</h3><p>Név, időpont, szoba. Befizetést és elérhetőséget csak akkor adj meg, ha szeretnéd követni.</p><a href="#demo">Kipróbálom <ArrowRight size={15}/></a></div></article>
    <article><div className="lp-example-visual calendar"><div className="lp-example-title"><BedDouble size={17}/>Szabad szobák<span>Minta</span></div><p>Október 16., péntek</p><div className="lp-mini-room"><strong>Fenyő</strong><span>Foglalt · Kiss Anna</span></div><div className="lp-mini-room free"><strong>Boróka</strong><span>Szabad · 2 fő</span></div><div className="lp-mini-room free"><strong>Kisház</strong><span>Szabad · 4 fő</span></div><div className="lp-mini-caption">Válassz egy napot a naptárban.</div></div><div className="lp-example-copy"><span>02 · ÚJ VENDÉG ÉRDEKLŐDIK</span><h3>Tudd, melyik szobád szabad.</h3><p>A havi naptárban egy pillantás az időpont. Egy koppintás a vendégek és a szabad szobák listája.</p><a href="#demo?view=calendar">Megnézem a naptárt <ArrowRight size={15}/></a></div></article>
    <article><div className="lp-example-visual guide"><div className="lp-example-title"><Wifi size={17}/>Vendégtudnivalók<span>Minta</span></div><div className="lp-mini-guide-brand">BORÓKA VENDÉGHÁZ<h4>Érezd magad otthon.</h4></div>{[[Wifi,'WiFi','A hálózat és a jelszó egy helyen.'],[Coffee,'Reggeli','8:00–10:00 · az étkezőben.'],[MapPin,'Parkolás','A ház előtti udvarban.']].map(([Icon,title,text])=><div className="lp-mini-guide-row" key={title}><Icon size={17}/><div><strong>{title}</strong><small>{text}</small></div></div>)}</div><div className="lp-example-copy"><span>03 · A VENDÉG KÉRDEZ</span><h3>A tudnivalókat is rendezd el.</h3><p>Készíts útmutatót a szállásodról. Letölthető oldallal, előnézettel és a nyilvános webcímedhez QR-kóddal.</p><a href="#demo?view=guide">Megnézem az útmutatót <ArrowRight size={15}/></a></div></article>
  </div><p className="lp-example-disclaimer">Szemléltető minták. A működő demóban minden kipróbálható, a saját munkaterületed a saját adataiddal indul.</p></section>;
}
